apiVersion: v1
kind: Service
metadata:
  name: contacts-service
  labels:
    app: contacts
spec:
  selector:
    app: contacts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  